services:
  dashyboard-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dashyboard-frontend
    ports:
      - "3000:80"
    depends_on:
      - dashyboard-api
    networks:
      - dashyboard-network

  dashyboard-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dashyboard-api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Swedavia__FlightInfoApiKey=${SWEDAVIA_FLIGHT_API_KEY}
      - Swedavia__WaitTimeApiKey=${SWEDAVIA_WAIT_TIME_API_KEY}
      - CheckWx__ApiKey=${CHECKWX_API_KEY}
    volumes:
      - ./backend/data:/app/data
    networks:
      - dashyboard-network

networks:
  dashyboard-network:
    driver: bridge
